/**
 * Predefined Activity/Antecedent strings for optional ABC Builder (note generation).
 * Frontend dropdowns must use these exact strings; POST /notes/generate validates against this list.
 */
export const ABC_ACTIVITY_ANTECEDENT_CATALOG: readonly string[] = [
  "RBT guided the client to work on a fine motor skill activity.",
  "RBT directed the client to work on a gross motor skill activity.",
  "RBT instructed the client for playing freeze dance.",
  "RBT instructed the client to play musical chairs.",
  "RBT instructed the client to follow the leader.",
  "RBT instructed the client to play charades.",
  "RBT instructed the client for playing Simon says.",
  "RBT asked the client to wait for preferred items.",
  "RBT asked the client to wait for a preferred activity.",
  "RBT prompted the client it was time for outdoor activities.",
  "RBT instructed the client to work with flashcards.",
  "RBT instructed the client to work with number flashcards.",
  "RBT instructed the client to work with color flashcards.",
  "RBT instructed the client to work with shapes flashcards.",
  "RBT instructed the client to greet another.",
  "RBT directed the client to share a toy.",
  "RBT directed the client to wait their turn.",
  "RBT prompted the client to visually track a person.",
  "RBT instructed the client to visually track an object.",
  "RBT instructed the client to wait during the transition.",
  "RBT prompted the client to wait for a break in conversation to interrupt.",
  'RBT stated "look at me."',
  "RBT prompted the client to work on a matching categories activity.",
  "RBT instructed the client to match identical pictures.",
  "RBT asked the client to match letters.",
  "RBT instructed the client to match non-identical pictures.",
  "RBT directed the client towards the building blocks activity.",
  "RBT prompted the client to complete a pattern activity.",
  "RBT guided the client to ignore a peer causing a distraction.",
  "RBT prompted the client to reciprocate comments about objects.",
  "RBT instructed the client to request attention.",
  "RBT guided the client to request an available item.",
  "RBT guided the client to request an available activity.",
  "RBT directed the client to request a break.",
  "RBT prompted the client to imitate a gesture.",
  "RBT instructed the client to complete the next activity on the chore list.",
  "RBT asked the client to describe the drawing.",
  "RBT asked the client to describe the picture.",
  "RBT asked the client to describe how the toy worked.",
  "RBT prompted the client with several shapes and asked the client to identify the shape.",
  "RBT prompted the client with several objects and asked the client to identify the objects.",
  "RBT instructed the client to join ongoing play with a peer.",
  "RBT instructed the client to follow multi-step instructions.",
  "RBT prompted the client with one-step instructions.",
  "RBT asked the client to ask vs. tell for the desired item.",
  "RBT instructed the client to come sit down.",
  "RBT prompted the client with two-step instructions.",
  "RBT prompted the client to clean up the workstation.",
  "RBT prompted the client to clean up the toys.",
  "RBT instructed the client to wait for the preferred item.",
  "RBT gave the client an instruction to work with a bouncy ball.",
  "RBT prompted the client it was not time for a break yet.",
  "RBT instructed the client to count objects from a set.",
  "RBT instructed the client to count objects on the table.",
  "RBT guided the client to follow worksheet instructions.",
  "RBT prompted the client to follow instructions that include negatives.",
  "RBT asked the client to stop the activity.",
  "RBT prompted the client to begin free play.",
  "RBT instructed the client to complete a pattern.",
  "RBT instructed the client to complete a puzzle.",
  "RBT instructed the client to complete a matching activity.",
  "RBT directed the client to follow the schedule to the next activity.",
  "RBT guided the client to wash hands.",
  "RBT guided the client to interrupt an appropriate conversation.",
  "RBT redirected the client to respond to yes and no questions.",
  "RBT instructed the client to wait.",
  "RBT asked the client to move an item from one location to another.",
  "RBT guided the client to color a picture.",
  "RBT prompted the client to color within the lines.",
  "RBT asked the client to begin the activity.",
  "RBT instructed the client to sit down at the workstation.",
  "RBT prompted the client to increase the difficulty of the task.",
  "RBT asked the client to return the tangible.",
  "RBT prompted the client with feedback.",
  'RBT prompted the client with a question - "What do you want?"',
  'RBT prompted the client with a question - "What\'s that?"',
  "RBT instructed the client to answer the question of another.",
  "RBT prompted the client to share toys with peers.",
  "RBT redirected the client to play with others.",
  "RBT asked the client to do a non-preferred activity.",
  "RBT prompted the client to start a new non-preferred task/activity.",
  'RBT told the client "NO" when it was not time to access a tangible.',
  'RBT told the client "NO" when it was not time to access a preferred activity.',
  'RBT told the client "NO" when it was not time to gain attention yet.',
  "RBT prompted the client to work on a non-preferred activity.",
  "RBT directed the client to start the transition from preferred to non-preferred activity.",
  "RBT transitioned from one activity to the next.",
  "After a change in the schedule, RBT directed the client to a different activity.",
  "Caregiver prompted the client to attend to the task.",
  "RBT made a request for the client to respond, and the request was ignored. RBT repeated the request.",
  "RBT delivered verbal instructions to the client.",
  "RBT prompted client to wait for the next instruction.",
  "RBT prompted the client to start a new task.",
  "RBT delivered instruction about a multi-step activity.",
  "RBT denied access to item/activity.",
  "RBT instructed the client about the transition between activities.",
  "RBT instructed the client about the transition between tasks.",
  "RBT did not provide access to attention.",
  "RBT directed client to follow sequence of tasks to be completed.",
  'RBT instructed client by stating "it is time for non-preferred activity."',
  "RBT asked the client to pay attention.",
  "RBT instructed the client to transition to the next activity.",
  "RBT gave the client an instruction to complete an activity.",
  "RBT gave the client an instruction to complete the task.",
  "RBT asked client to wait during transition.",
  "RBT prompted the client to clean up the blocks.",
  "RBT prompted the client to clean up the table.",
  "The client was distracted by the TV, the RBT turned the TV off.",
  "The client was distracted by the tablet or iPad, the RBT turned the tablet off.",
  "RBT did not provide clients with access to preferred item.",
  "RBT instructed the client to complete an assigned task.",
  "RBT instructed the client to complete planned activity.",
] as const;

const catalogSet = new Set<string>(ABC_ACTIVITY_ANTECEDENT_CATALOG);

export function isValidAbcActivityAntecedent(value: string): boolean {
  return catalogSet.has(value);
}
