/** Prompt section: function-based ABC correction (topography + intervention + replacement alignment). */
export const FUNCTION_BASED_ABC_CORRECTION_PROMPT = `FUNCTION-BASED ABC CORRECTION (mandatory when maladaptiveBehaviorFunctionsForHour[s] is non-empty):
- **Primary objective:** Each maladaptive segment must have (A) a concrete antecedent with materials/RBT actions, (B) an observable topography in the manifested-behavior line (never the catalog label alone), (C) catalog intervention(s) that match the **documented function**, and (D) replacement-program teaching that matches the same function via the assigned verbatim replacementProgramForHour[s].
- **Attention-maintained:** Name **DRA or DRI** when listed (required as the function intervention after Response Block on safety-priority segments). In **Following this intervention,** document withholding attention during the maladaptive topography and delivering reinforcement only after appropriate engagement, communication, or hands-down/compatible behavior. Pair with a **social/communication** replacement from behaviorReplacementCandidatesForHour[s] (FCT, Functional communication to request attention, Appropriate social skills, sharing/turn-taking when BIP-mapped)—teach that skill observably in the replacement-program sentence.
- **Escape-maintained:** Use demand/escape interventions from interventionCandidatesForHour[s] (Escape Extinction, Demand Fading, Escape independent response delivery, Premack principle, or DRA when listed). In **Following this intervention,** document re-presentation of the task, prompting, and structured follow-through. Pair with compliance/task-engagement replacements (Request for Break, Follow Instructions, Remaining seated completing the task, Following Non-preferred instructions, On task Behavior—only when BIP-mapped). Reinforce task completion or appropriate responding after withholding escape.
- **Tangible-maintained:** Use access/contingency interventions from interventionCandidatesForHour[s] (DRA, Premack principle, token economy, tangible extinction when listed). In **Following this intervention,** document withheld preferred access during the maladaptive response and delivery only after appropriate requesting, waiting, or compatible behavior. Pair with tangible-function replacements (Request for Tangible, Accept "No", sharing/turn-taking, Accepting alternatives—only when BIP-mapped).
- **ABC consistency:** Antecedent demand/access/social context must match why the behavior occurred; consequence must describe withholding during topography then reinforcement tied to the replacement skill—not vague return or praise during the maladaptive episode.
- **Quality check before output:** (1) topography is specific and observable, (2) every named intervention matches documented function (Response Block is safety-only—never the sole function intervention when candidates exist), (3) replacement teaching aligns with function and BIP map, (4) tone stays objective, measurable, and audit-ready.`;

/** Extra revision-mode reminders when compliance repair runs. */
export const FUNCTION_BASED_CORRECTION_REVISION_HINTS = `Apply **FUNCTION-BASED ABC CORRECTION** from the base prompt: rewrite mismatched interventions to match maladaptiveBehaviorFunctionsForHour[s]; use interventionCandidatesForHour[s] and behaviorReplacementCandidatesForHour[s]; for attention-maintained SIB/aggression with Response Block first, second intervention must be DRA/DRI when listed (not Attention independent response delivery alone); strengthen thin manifested-behavior lines with observable "manifested [label] by …" topography from maladaptiveBehaviorTopographyForHour[s] when set; align replacement-program "by …" teaching to the assigned program's function.`;
